const ActionTypes = {
  GET_COLUMNS: 'GET_COLUMNS',
  ADD_COLUMN: 'ADD_COLUMN',
  EDIT_COLUMN: 'EDIT_COLUMN',
  DELETE_COLUMN: 'DELETE_COLUMN',
  GET_CARDS: 'GET_CARDS',
  GET_CARD_BY_ID: 'GET_CARD_BY_ID',
  ADD_CARD: 'ADD_CARDS',
  EDIT_CARD: 'EDIT_CARD',
  DELETE_CARD: 'DELETE_CARD',
};

export default ActionTypes;
